Update README (GA)
slack-samples/deno-github-functions pull request #22
Opened 2023-04-21 23:27 UTC by misscoded

### Type of change (place an x in the [ ] that applies)

- [ ] New sample
- [ ] New feature
- [ ] Bug fix
- [x] Documentation

### Summary

Update README with updated structure.

### Requirements (place an x in each [ ] that applies)

- [x] I’ve checked my submission against the Samples Checklist to ensure it complies with all standards
- [x] I have ensured the changes I am contributing align with existing patterns and have tested and linted my code
- [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct)

2023-04-28 02:27 UTC, e-zim requested changes
Thank you once more for making all of these improvements! 🙇

Left a few comments on the datastore sections included for this sample that I think are worth removing, and one on a small note about potentially including the guide from the docs.

Everything else is really solid, so will following any changes with an approval!

2023-04-28 02:27 UTC, e-zim commented on README.md
> +This sample demonstrates how to create automation in Slack using GitHub.
```suggestion
This sample demonstrates automations in Slack that interact with the GitHub API.
```

Feel free to adjust this or ignore, but I think guides do more wholistic job of demonstrating "how to create" than the sample. Maybe we also include [the guide](https://api.slack.com/tutorials/tracks/create-github-issues-in-workflows) in the README?

2023-04-28 02:27 UTC, e-zim commented on README.md
>  ## Project Structure
Could we also include the `external_auth/` section found on [the timesheet approval sample](https://github.com/slack-samples/deno-timesheet-approval#external_auth)?

2023-04-28 02:27 UTC, e-zim commented on README.md
> +include `datastore:write` and `datastore:read`.
This sample doesn't include this, so I think this section can be removed!

2023-04-28 02:27 UTC, e-zim commented on README.md
> +`datastore:write`/`datastore:read` scopes to be present in your manifest.
I believe this section can be removed for this sample! 🚫🗄️!

2023-04-28 02:27 UTC, e-zim commented on README.md
> +- [Datastores](#datastores)
```suggestion
```

Some comments on this are below!

2023-04-28 02:27 UTC, e-zim commented on README.md
> -# Workflows for GitHub Sample App
A very welcomed change to this header 🙌

2023-10-30 22:37 UTC, misscoded commented
No longer relevant. Closing.

2023-10-30 22:37 UTC, closed without merging